#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source $DIR/secret.sh

node $DIR/add-schedule/schedule-twitch
node $DIR/add-schedule/schedule-html

git add $DIR/../schedule.html
git add $DIR/tools/add-schedule/schedule.org

git commit -m "schedule: regenerated html schedule"
